version: '3.9'

services:
  fastapi:
    build: .
    container_name: my-fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]